services:
  database:
    image: mysql:8.0.41
    volumes:
      - "./imageData/dbdata:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=super"
      - "TZ=Asia/Shanghai"
    ports:
      - "33306:3306"
  redis:
    image: redis:7.2
    ports:
      - "36379:6379"
    volumes:
      - "./imageData/redis_data:/bitnami/redis/data"
