app:
  env: "dev"
  name: "go-mall"
  log:
    path: "/Users/lyydsheep/workspace/Go/projects/go-mall/log/go-mall.log"
    maxSize: 100
    maxAge: 60
  pagination:
    defaultSize: 20
    maxSize: 100
db:
  type: "mysql"
  dsn: "reserved"
  maxIdleCons: 100
  maxIdleTime: 120
  maxLifeTime: 360
