app:
  env: "dev"
  name: "go-mall"
  log:
    # 日志文件路径，从项目路径开始出发
    path: "./tmp/go-mall.log"
    # 文件最大体积（M）和有效期（Day）
    max_size: 1
    max_age: 60
database:
  type: "mysql"
  dsn: "reserved"
  max_open: 100
  max_idle: 100
  max_life_time: 300
